/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.JOptionPane;

/**
 *
 * @author FCOST
 */
public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public CadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lbCrieUmaSenha = new javax.swing.JLabel();
        lbConfirmeASenha = new javax.swing.JLabel();
        btCriarConta = new javax.swing.JButton();
        pfConfirmaSenha = new javax.swing.JPasswordField();
        tfNome = new javax.swing.JTextField();
        pfSenha = new javax.swing.JPasswordField();
        lbDigiteSeuNome = new javax.swing.JLabel();
        lbCadastrese = new javax.swing.JLabel();
        jLLogar = new javax.swing.JLabel();
        imgPainel = new javax.swing.JLabel();
        btLogar = new javax.swing.JButton();
        imgFundo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cozinhe com mais praticidade");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cozinha com Afeto - Login");
        setMinimumSize(new java.awt.Dimension(870, 580));
        getContentPane().setLayout(null);

        lbCrieUmaSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCrieUmaSenha.setText("Crie uma senha");
        getContentPane().add(lbCrieUmaSenha);
        lbCrieUmaSenha.setBounds(550, 230, 100, 16);

        lbConfirmeASenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbConfirmeASenha.setText("Confirme a senha");
        getContentPane().add(lbConfirmeASenha);
        lbConfirmeASenha.setBounds(550, 290, 140, 16);

        btCriarConta.setBackground(new java.awt.Color(254, 136, 1));
        btCriarConta.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btCriarConta.setForeground(new java.awt.Color(255, 255, 255));
        btCriarConta.setText("CRIAR CONTA");
        btCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarContaActionPerformed(evt);
            }
        });
        getContentPane().add(btCriarConta);
        btCriarConta.setBounds(560, 380, 200, 40);
        getContentPane().add(pfConfirmaSenha);
        pfConfirmaSenha.setBounds(550, 310, 220, 22);

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tfNome);
        tfNome.setBounds(550, 190, 220, 22);
        getContentPane().add(pfSenha);
        pfSenha.setBounds(550, 250, 220, 22);

        lbDigiteSeuNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDigiteSeuNome.setText("Digite seu nome");
        getContentPane().add(lbDigiteSeuNome);
        lbDigiteSeuNome.setBounds(550, 170, 100, 16);

        lbCadastrese.setBackground(new java.awt.Color(0, 0, 0));
        lbCadastrese.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lbCadastrese.setForeground(new java.awt.Color(254, 136, 1));
        lbCadastrese.setText("Cadastre-se");
        getContentPane().add(lbCadastrese);
        lbCadastrese.setBounds(590, 110, 140, 30);

        jLLogar.setText("Já tem uma conta?");
        getContentPane().add(jLLogar);
        jLLogar.setBounds(550, 340, 120, 16);

        imgPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PanelUser.png"))); // NOI18N
        getContentPane().add(imgPainel);
        imgPainel.setBounds(490, 30, 350, 490);

        btLogar.setText("Já tem uma conta?");
        btLogar.setBorder(null);
        btLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogarActionPerformed(evt);
            }
        });
        getContentPane().add(btLogar);
        btLogar.setBounds(550, 340, 140, 16);

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Inserir um título.png"))); // NOI18N
        getContentPane().add(imgFundo);
        imgFundo.setBounds(0, 0, 860, 540);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registre criações");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 120, 470, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void btCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarContaActionPerformed
        // TODO add your handling code here: 
    Usuario.nomeUsuario = tfNome.getText().trim();
    
      if (Usuario.nomeUsuario.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Digite um nome antes de continuar!");
        return; 
    }
    String nome = tfNome.getText();
    String senha = new String(pfSenha.getPassword());
    String confirmaSenha = new String(pfConfirmaSenha.getPassword());
    if (nome.isEmpty() || senha.isEmpty() || confirmaSenha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
        
        }
    if (!senha.equals(confirmaSenha)) {
        JOptionPane.showMessageDialog(this, "As senhas não coincidem!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }
    Usuario.nomeUsuario = nome;
    Usuario.senhaUsuario = senha;
    
    JOptionPane.showMessageDialog(this, "Conta criada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    UsuarioEntrar login = new UsuarioEntrar();
    login.setVisible(true);
    login.setLocationRelativeTo(null);
    this.dispose();

    }//GEN-LAST:event_btCriarContaActionPerformed
    
    private void btLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogarActionPerformed
        // TODO add your handling code here:
    UsuarioEntrar login = new UsuarioEntrar(); 
    login.setVisible(true);
    login.setLocationRelativeTo(null);
    this.dispose();
    
    }//GEN-LAST:event_btLogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCriarConta;
    private javax.swing.JButton btLogar;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JLabel imgPainel;
    private javax.swing.JLabel jLLogar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbCadastrese;
    private javax.swing.JLabel lbConfirmeASenha;
    private javax.swing.JLabel lbCrieUmaSenha;
    private javax.swing.JLabel lbDigiteSeuNome;
    private javax.swing.JPasswordField pfConfirmaSenha;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
