


import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

    
     
   
 
public class TelaPrincipal extends javax.swing.JFrame {

    private Object ingredientes;

    public TelaPrincipal() {
        
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnCima = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbIngredientes = new javax.swing.JLabel();
        lbModoPreparo = new javax.swing.JLabel();
        lbOrigem = new javax.swing.JLabel();
        lbTempoPreparo = new javax.swing.JLabel();
        lbFonte = new javax.swing.JLabel();
        lbAdicoes = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        tfIngredientes = new javax.swing.JTextField();
        tfModoPreparo = new javax.swing.JTextField();
        tfOrigem = new javax.swing.JTextField();
        tfTempoPreparo = new javax.swing.JTextField();
        tfFonte = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUltimasAdicoes = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btAdicionar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        Mopcoes = new javax.swing.JMenu();
        JClogin = new javax.swing.JCheckBoxMenuItem();
        JCsair = new javax.swing.JCheckBoxMenuItem();
        jMCadastrar = new javax.swing.JMenu();
        jCMinhasReceitas = new javax.swing.JCheckBoxMenuItem();

        jLabel7.setText("jLabel7");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnCima.setBackground(new java.awt.Color(230, 94, 41));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cópia de PROTOTIO3.pdf (2) (2) (2).png"))); // NOI18N

        javax.swing.GroupLayout pnCimaLayout = new javax.swing.GroupLayout(pnCima);
        pnCima.setLayout(pnCimaLayout);
        pnCimaLayout.setHorizontalGroup(
            pnCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCimaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(imgLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCimaLayout.setVerticalGroup(
            pnCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCimaLayout.createSequentialGroup()
                .addComponent(imgLogo)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        lbTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbTitulo.setText("Título da receita:");

        lbIngredientes.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbIngredientes.setText("Ingredientes:");

        lbModoPreparo.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbModoPreparo.setText("Modo de preparo:");

        lbOrigem.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbOrigem.setText("Origem:");

        lbTempoPreparo.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbTempoPreparo.setText("Tempo de preparo:");

        lbFonte.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbFonte.setText("Fonte:");

        lbAdicoes.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbAdicoes.setText("Últimas adições:");

        tfTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tfTitulo.setForeground(new java.awt.Color(102, 102, 102));

        tfIngredientes.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tfIngredientes.setForeground(new java.awt.Color(102, 102, 102));
        tfIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIngredientesActionPerformed(evt);
            }
        });

        tfModoPreparo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tfModoPreparo.setForeground(new java.awt.Color(102, 102, 102));

        tfOrigem.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tfOrigem.setForeground(new java.awt.Color(102, 102, 102));

        tfTempoPreparo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tfTempoPreparo.setForeground(new java.awt.Color(102, 102, 102));

        tfFonte.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tfFonte.setForeground(new java.awt.Color(102, 102, 102));

        tbUltimasAdicoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prato", "Ingredientes", "Tempo de preparo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbUltimasAdicoes);

        btExcluir.setBackground(new java.awt.Color(230, 94, 41));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ApagarImg.png"))); // NOI18N
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btEditar.setBackground(new java.awt.Color(44, 44, 44));
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Editar.png"))); // NOI18N
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btAdicionar.setBackground(new java.awt.Color(230, 94, 41));
        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AdicionarImg.png"))); // NOI18N
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(44, 44, 44));
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LimparImg.png"))); // NOI18N
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        jMenuBar2.setBackground(new java.awt.Color(230, 94, 41));
        jMenuBar2.setForeground(new java.awt.Color(230, 94, 41));

        Mopcoes.setText("Opções");

        JClogin.setSelected(true);
        JClogin.setText("Login");
        Mopcoes.add(JClogin);

        JCsair.setSelected(true);
        JCsair.setText("Sair");
        JCsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCsairActionPerformed(evt);
            }
        });
        Mopcoes.add(JCsair);

        jMenuBar2.add(Mopcoes);

        jMCadastrar.setText("Receitas");

        jCMinhasReceitas.setSelected(true);
        jCMinhasReceitas.setText("Minhas Receitas");
        jCMinhasReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCMinhasReceitasActionPerformed(evt);
            }
        });
        jMCadastrar.add(jCMinhasReceitas);

        jMenuBar2.add(jMCadastrar);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIngredientes)
                    .addComponent(lbModoPreparo)
                    .addComponent(tfModoPreparo)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addComponent(tfIngredientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbFonte)
                            .addComponent(lbOrigem)
                            .addComponent(lbTempoPreparo)
                            .addComponent(lbAdicoes))
                        .addGap(255, 255, 255))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfOrigem, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTempoPreparo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(tfFonte, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnCima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(lbOrigem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIngredientes)
                    .addComponent(lbTempoPreparo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfTempoPreparo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbFonte)
                        .addGap(5, 5, 5)
                        .addComponent(tfFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAdicoes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbModoPreparo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfModoPreparo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btExcluir)
                    .addComponent(btEditar)
                    .addComponent(btAdicionar)
                    .addComponent(btLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int selectRow=tbUltimasAdicoes.getSelectedRow();
        if(selectRow!=-1){
            DefaultTableModel model=(DefaultTableModel) tbUltimasAdicoes.getModel();
            model.removeRow(selectRow);
            JOptionPane.showMessageDialog(this, "Receita excluída com sucesso!");
            
        }else{
            JOptionPane.showMessageDialog(this, "Selecione a receita para excluir");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        int selectedRow=tbUltimasAdicoes.getSelectedRow();
        if (selectedRow!=-1) {
        DefaultTableModel model=(DefaultTableModel) tbUltimasAdicoes.getModel();
        tfTitulo.setText(model.getValueAt(selectedRow, 0).toString());
        tfIngredientes.setText(model.getValueAt(selectedRow, 1).toString());
        tfTempoPreparo.setText(model.getValueAt(selectedRow, 2).toString());
        JOptionPane.showMessageDialog(this, "Edite os campos e clique em adicionar para atualizar.");
    } else {
        JOptionPane.showMessageDialog(this, "Selecione uma receita para editar.");
    }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
        String titulo=tfTitulo.getText();
        String ingrediente =tfIngredientes.getText();
        String tempoPreparo=tfTempoPreparo.getText();
        

        if (titulo.trim().isEmpty()||ingrediente.trim().isEmpty()||tempoPreparo.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos antes de adicionar!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

        DefaultTableModel model = (DefaultTableModel) tbUltimasAdicoes.getModel();
        model.addRow(new Object[]{titulo, ingrediente, tempoPreparo});

        JOptionPane.showMessageDialog(this, "Receita adicionada com sucesso!");
        limparCampos();
 
    }//GEN-LAST:event_btAdicionarActionPerformed
    
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
        
    }//GEN-LAST:event_btLimparActionPerformed
    private void limparCampos() {     
        tfTitulo.setText("");
        tfIngredientes.setText("");
        tfModoPreparo.setText("");
        tfOrigem.setText("");
        tfTempoPreparo.setText("");
        tfFonte.setText("");
        

    }                    
    private void tfIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIngredientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIngredientesActionPerformed

    private void JCsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCsairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_JCsairActionPerformed

    private void jCMinhasReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCMinhasReceitasActionPerformed
        // TODO add your handling code here:
        abrirTelaPagina();
    }//GEN-LAST:event_jCMinhasReceitasActionPerformed
    private void abrirTelaPagina() {
    TelaPágina telaPagina = new TelaPágina(); 
    telaPagina.setVisible(true);
    this.dispose();
} 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem JClogin;
    private javax.swing.JCheckBoxMenuItem JCsair;
    private javax.swing.JMenu Mopcoes;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JCheckBoxMenuItem jCMinhasReceitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMCadastrar;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAdicoes;
    private javax.swing.JLabel lbFonte;
    private javax.swing.JLabel lbIngredientes;
    private javax.swing.JLabel lbModoPreparo;
    private javax.swing.JLabel lbOrigem;
    private javax.swing.JLabel lbTempoPreparo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnCima;
    private javax.swing.JTable tbUltimasAdicoes;
    private javax.swing.JTextField tfFonte;
    private javax.swing.JTextField tfIngredientes;
    private javax.swing.JTextField tfModoPreparo;
    private javax.swing.JTextField tfOrigem;
    private javax.swing.JTextField tfTempoPreparo;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
    }

